//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakkkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class about
    {
        public int aboutId { get; set; }
        public string aboutContent { get; set; }
        public string aboutImage { get; set; }
        public string mail { get; set; }
        public string adress { get; set; }
        public Nullable<int> phone { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string instagram { get; set; }
        public string pinterest { get; set; }
        public string linkedin { get; set; }
        public string youtube { get; set; }
    }
}
