//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakkkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class details
    {
        public int detailId { get; set; }
        public Nullable<int> productId { get; set; }
        public string deposit { get; set; }
        public Nullable<int> squareMeters { get; set; }
        public string roomQuantity { get; set; }
        public string floor { get; set; }
        public string heatingType { get; set; }
        public Nullable<int> BuildingAge { get; set; }
        public string fromWho { get; set; }
        public string buildingStatus { get; set; }
        public string attachments { get; set; }
    
        public virtual products products { get; set; }
    }
}
