//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakkkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class features
    {
        public int featureId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> carPark { get; set; }
        public Nullable<int> swapability { get; set; }
        public Nullable<int> eligibilityForCredit { get; set; }
        public Nullable<int> furnitureStatus { get; set; }
        public Nullable<int> dues { get; set; }
        public Nullable<int> swimmingPool { get; set; }
        public Nullable<int> sauna { get; set; }
        public Nullable<int> airConditioning { get; set; }
        public Nullable<int> gym { get; set; }
        public Nullable<int> wifi { get; set; }
    
        public virtual products products { get; set; }
    }
}
