//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakkkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int messageId { get; set; }
        public Nullable<int> fromUser { get; set; }
        public Nullable<int> toUser { get; set; }
        public string messaceContent { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
