//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakkkk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class emlksisEntities : DbContext
    {
        public emlksisEntities()
            : base("name=emlksisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<about> about { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<counties> counties { get; set; }
        public virtual DbSet<details> details { get; set; }
        public virtual DbSet<favorites> favorites { get; set; }
        public virtual DbSet<features> features { get; set; }
        public virtual DbSet<images> images { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<posts> posts { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<provinces> provinces { get; set; }
        public virtual DbSet<sss> sss { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
