//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakkkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        public int postId { get; set; }
        public Nullable<int> userId { get; set; }
        public string postTitle { get; set; }
        public string postContent { get; set; }
        public string postTag { get; set; }
        public string postImage { get; set; }
        public Nullable<System.DateTime> releaseDate { get; set; }
    
        public virtual users users { get; set; }
    }
}
