//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakkkk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.details = new HashSet<details>();
            this.favorites = new HashSet<favorites>();
            this.features = new HashSet<features>();
            this.images = new HashSet<images>();
        }
    
        public int productId { get; set; }
        public Nullable<int> userId { get; set; }
        public string productName { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
        public string type { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string countryName { get; set; }
        public Nullable<int> countyId { get; set; }
        public string adress { get; set; }
        public Nullable<System.DateTime> releaseDate { get; set; }
        public string latLong { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual counties counties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<details> details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorites> favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<features> features { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<images> images { get; set; }
        public virtual users users { get; set; }
    }
}
